# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'bubble-wrap/core'
require 'bubble-wrap/camera'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'KeyHook'
  app.info_plist['UIViewControllerBasedStatusBarAppearance'] = false
end
