# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
$:.unshift("~/.rubymotion/rubymotion-templates")

require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  app.name = 'Tasker'

  app.info_plist["UIViewControllerBasedStatusBarAppearance"] = false
  app.info_plist['UIStatusBarStyle'] = 'UIStatusBarStyleLightContent'
end
task :"build:simulator" => :"schema:build"
