# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion2.11/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'OneTweetWorld'

  app.redgreen_style = :full
end
