# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  app.name = 'Tasker'

  app.info_plist["UIViewControllerBasedStatusBarAppearance"] = false
  app.info_plist['UIStatusBarStyle'] = 'UIStatusBarStyleLightContent'

  app.pods do
    pod 'RestKit'
    pod 'SVProgressHUD'
    pod 'MHPrettyDate'
  end
end
task :"build:simulator" => :"schema:build"
